Conditionally unconvert style and children props
Workiva/over_react pull request #698
Opened 2021-07-30 01:29 UTC by greglittlefield-wf

## Motivation
Sometimes, Dart code can read props that originate from JS code (e.g., a JS component rendering/cloning a Dart component), and in cases where the JS prop value doesn't match the typings on the OverReact prop getter, you get a runtime type error.

Two common cases of this are the `style` and `children` props.

`style` props set by JS code are JS objects, which can't be casted to Dart `Map`s in the `DomPropsMixin.style` and `UbiquitousDomPropsMixin.style` getters.

`children` props are always `List`s for Dart components rendered by Dart code, but can be nullish or a singular value when rendered by JS components, and can cause cast errors in the typed `children` prop getter.

## Changes
- Normalize the value of the `children` prop getter (`ReactPropsMixin.children`, mixed into `UiProps`) to always be a `List`
- Normalize the value of the `style` prop getters (`UbiquitousDomPropsMixin.style`, mixed into `UiProps`, and `DomPropsMixin.style`) to convert JS object values to Dart `Map`s
- Add tests

#### Release Notes
  

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        - [ ] All existing tests pass
        - [ ] Test in major consumer repos to ensure these changes don't cause any issues
        - [ ] JS component test cases in RMUI branch pass
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-criteria

2021-07-30 01:31 UTC, greglittlefield-wf commented on lib/src/component/prop_mixins.dart
> +  List<dynamic> get children {
I inlined this implementation into the getter, as opposed to making it a utility function, so that I could do `props.containsKey('children')` below

2021-07-30 01:31 UTC, aviary-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2021-08-03 13:38 UTC, aaronlademann-wf approved these changes
This looks great! Awesome test coverage!

2021-08-03 13:46 UTC, aaronlademann-wf requested changes
-1

- [w_table consumer test failures](https://wf-skynet-hrd.appspot.com/apps/test/smithy/2995558/1/w_table/unit-tests-dart2js#summary) appear related to these changes

2021-08-04 16:14 UTC, aaronlademann-wf approved these changes
+1

w_table consumer test failures were a red herring

+10 

- [x] Dart 2.7.2 / Stable CI builds and tests passed
- [x] consumer tests with the exception of a few known flaky tests passed

@Workiva/release-management-pp

2021-08-04 16:15 UTC, rmconsole-wf approved these changes
+1 from RM

2021-08-04 16:15 UTC, merged