CPLAT-17301 Update AriaPropsMixin
Workiva/over_react pull request #742
Opened 2022-05-03 16:00 UTC by sydneesampson-wk

## Motivation
Update AriaPropsMixin with missing attributes

## Changes
Added missing Aria attributes
Added missing Aria roles
Updated outdated W3 links
Add new documentation

#### Release Notes
  

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/over_react/blob/master/CONTRIBUTING.md#manual-testing-criteria

2022-05-03 16:14 UTC, brianphillips-wk commented on lib/src/component/aria_mixin.dart
> +
You can remove this

```suggestion
```

2022-05-03 16:17 UTC, brianphillips-wk commented on lib/src/component/aria_mixin.dart
> +   Accessor(key: 'aria-description')
```suggestion
   @Accessor(key: 'aria-description')
```

2022-05-03 16:18 UTC, brianphillips-wk commented on lib/src/component/aria_mixin.dart
> +
Be sure to run `ddev format` to get all the spacing lined up

2022-05-05 23:26 UTC, brianphillips-wk submitted a review, later dismissed
Slight tweaks here—Dart requires semicolons, hence the build failures

2022-05-05 23:26 UTC, brianphillips-wk commented on lib/src/component/aria_mixin.dart
> +  String aria-rowindextext
Quick fix:

```suggestion
  String rowindextext;
```

2022-05-05 23:26 UTC, brianphillips-wk commented on lib/src/component/aria_mixin.dart
> +  static const String table = 'table'
```suggestion
  static const String table = 'table';
```

2022-05-06 19:04 UTC, greglittlefield-wf requested changes
Two tiny things otherwise this looks great.

Thanks for updating all the doc comments, too!

2022-05-06 19:04 UTC, greglittlefield-wf commented on lib/src/component/aria_mixin.dart
> +  ///See: <https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes>
This comment will get attached to `activedescendant`; could we move it to the doc comment above the `_ $AriaPropsMixin` class?

2022-05-06 19:04 UTC, greglittlefield-wf commented on lib/src/component/aria_mixin.dart
> +  String error;
Is there a reason this is `error` instead of `errormessage`?
```suggestion
  String errormessage;
```

2022-05-06 20:34 UTC, sydneesampson-wk commented
Looks like the build is failing on the analyzer test check, but this seems to be failing on the master branch as well. Please let me know how to go about this

2022-05-09 16:41 UTC, greglittlefield-wf commented
@sydneesampson-wk We should be able to ignore that check for now, sorry about that!

2022-05-09 16:45 UTC, aaronlademann-wf reviewed
Looks great! Just had one nitpick about a doc comment location

2022-05-09 16:45 UTC, aaronlademann-wf commented on lib/src/component/aria_mixin.dart
> +
For this - when "documenting" an entire page / library, we usually put them above the library directive. In this case - that is on line 15...

```dart
/// See: <https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes>
library over_react.aria_mixin;
```

2022-05-09 16:45 UTC, rmconsole-wf approved these changes
+1 from RM

2022-05-09 16:45 UTC, merged